#!/usr/bin/env python

import bluerov.video as Video
import rospy
from cv_bridge import CvBridge
from sensor_msgs.msg import Image,CompressedImage

def main():
    try:
        rospy.init_node('camera_node', log_level=rospy.DEBUG)
    except rospy.ROSInterruptException as error:
        print('pubs error with ROS: ', error)
        exit(1)


    udp_port = rospy.get_param("/camera_node/udp_port", 5600)
    framerate = rospy.get_param("/camera_node/framerate", 30)
    rospy.loginfo("udp_port: {}".format(udp_port))
    rate = rospy.Rate(framerate)

    video = Video.Video(udp_port)
    video_bridge = CvBridge()
    image_pub = rospy.Publisher("BlueRov2/camera/image_raw",Image,queue_size=10)

    model_base_link = '/base_link'
    while True:
        if not video.frame_available():
            continue

        frame = video.frame()
        msg = video_bridge.cv2_to_imgmsg(frame, "bgr8")
        msg.header.stamp = rospy.Time.now()
        msg.header.frame_id = model_base_link
        image_pub.publish(msg)
        rate.sleep()

if __name__ == '__main__':
    main()


