#!/usr/bin/env python

import argparse
import bluerov_node as BR
import rospy
try:
    rospy.init_node('user_node', log_level=rospy.DEBUG)
except rospy.ROSInterruptException as error:
    print('pubs error with ROS: ', error)
    exit(1)

device = rospy.get_param("/node/device", 'udp:192.168.2.1:14550')
joy_mode= rospy.get_param("/node/joy_mode", 'Global')
joy= rospy.get_param("/node/joy", 'true')
print('Running with device', device)
bluerov = BR.BlueRov(device=device,joy_mode=joy_mode,joy=joy)
rate = rospy.Rate(30)
while not rospy.is_shutdown():
    bluerov.publish()
    rate.sleep()
